### ISSUE TITLE
Feature request, ability to run python file

### ISSUE THREAD

**Issue by deMartiniFrancesco** [jannekem/run-python-script-action#12]
### Description
Ability to specify a file to run instead of the pure python script

_Example:_
```yml
- uses: actions/setup-python@v4
  with:
    python-version: '3.x'
- uses: jannekem/run-python-script-action@v1
  with:
    file: path/to/script.py
```

### Seggestion
- [ ] Ability to run python file
- [ ] Ability to run python files on a specific branch

**Comment by jannekem** [comment]
Why would you need an action to run a Python script when you can already do so with the `run` keyword?

```yaml
- uses: actions/setup-python@v4
  with:
    python-version: '3.x'
- run: python3 path/to/script.py
```

**Comment by FrenkyDema** [comment]
I tried to use the `run` command but apparently it would seem to run the file only on the branch master, even if previously it was the checkout of the branch target.

**Comment by FrenkyDema** [comment]
For example, my Python file performs changes to project files, and my goal is to commission these modified files in the destination branch

**Comment by FrenkyDema** [comment]
### My action steps


```yml
- name: Checkout repo content
  uses: actions/checkout@v3 # checkout the repository content to GitHub runner
  with:
    repository: ${{ github.event.pull_request.head.repo.full_name }}
    ref: ${{ github.event.pull_request.head.ref }}

- name: Setup python
  uses: actions/setup-python@v4
  with:
    python-version: "3.10" # install the python version needed

- name: Install python packages
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    
- name: Execute py script
  run: python3 path/to/script.py

- name: Check diff
  uses: technote-space/get-diff-action@v6
  with:
    FILES: |
      target_file.txt
      
- name: Commit files
  run: |
    git config --local user.email "action@github.com"
    git config --local user.name "GitHub Action"
    git add -A
    git commit -m "bot: Update file" -a
  if: env.GIT_DIFF && env.MATCHED_FILES

- name: Push changes
  uses: ad-m/github-push-action@v0.6.0
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    branch: master
  if: env.GIT_DIFF && env.MATCHED_FILES
```

**Comment by deMartiniFrancesco** [comment]
I tried to use the `run` command but apparently it would seem to run the file only on the branch master, even if previously it was the checkout of the branch target.

For example, my Python file performs changes to project files, and my goal is to commission these modified files in the destination branch


### My action steps


```yml
- name: Checkout repo content
  uses: actions/checkout@v3 # checkout the repository content to GitHub runner
  with:
    repository: ${{ github.event.pull_request.head.repo.full_name }}
    ref: ${{ github.event.pull_request.head.ref }}

- name: Setup python
  uses: actions/setup-python@v4
  with:
    python-version: "3.10" # install the python version needed

- name: Install python packages
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    
- name: Execute py script
  run: python3 path/to/script.py

- name: Check diff
  uses: technote-space/get-diff-action@v6
  with:
    FILES: |
      target_file.txt
      
- name: Commit files
  run: |
    git config --local user.email "action@github.com"
    git config --local user.name "GitHub Action"
    git add -A
    git commit -m "bot: Update file" -a
  if: env.GIT_DIFF && env.MATCHED_FILES

- name: Push changes
  uses: ad-m/github-push-action@v0.6.0
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    branch: master
  if: env.GIT_DIFF && env.MATCHED_FILES
```
