### ISSUE TITLE
Provide functions to set outputs and environment variables

### ISSUE THREAD

**Issue by brechtm** [jannekem/run-python-script-action#3]
Just an idea that would make run-python-script-action even better.

I think the main use case is to set output or environment variables. run-python-script-action could provide functions to make this easier. You can prepend `import gha` to the script (perhaps controlled by an option) which provides these functions:

```python
def set_output(name, value):
    print(f'::set-output {name}=stable::{value}')

def set_env(name, value):
    with open(os.getenv('GITHUB_ENV'), 'a') as env:
        print(f'{name}={value}', file=env)
```

So then a user could do something like:

```yaml
- name: Find path to wheel
  uses: jannekem/run-python-script-action@v1
  with:
    script: |
      import os
      from pathlib import Path
      wheel_path = str(next(Path('dist').glob('*.whl')))
      gha.set_env('WHEEL_PATH', wheel_path)
```

Even better would be to also collect all output and environment variables and (optionally) print their names/values to the log, which can help with debugging.
